export { default as PHome } from './PHome'
export { default as PAuth } from './PAuth'
export { default as PAddCard } from './PAddCard'
export { default as PAddGame } from './PAddGame'
export { default as PGame } from './PGame'
